[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn app_2:app --host 0.0.0.0 --port $PORT"
numReplicas = 1
healthcheckPatch = "/health"
healthcheckTimeout = 60
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1